name: CI
env:
  DEBUG: napi:*
  APP_NAME: node
  MACOSX_DEPLOYMENT_TARGET: "10.13"
permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - "**/*.gitignore"
      - .editorconfig
      - docs/**

jobs:
  call-rust-build:
    uses: ./.github/workflows/rust-build.yml

  release:
    name: "release"
    needs: [call-rust-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
          run_install: false
      - uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts
      - name: View Artifact
        run: |
          mkdir /tmp/artifacts/transformer
          mv /tmp/artifacts/**/*.node /tmp/artifacts/transformer
          ls /tmp/artifacts/transformer
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: |
          pnpm --filter "@oomm/transformer" run build:rs
          pnpm --filter "@oomm/transformer" run clean
          pnpm --filter "@oomm/transformer" run build:release
      - name: Artifact
        run: |
          pnpm --filter "@oomm/transformer" exec mkdir ./tmp
          pnpm --filter "@oomm/transformer" exec mv /tmp/artifacts/transformer ./tmp
          pnpm --filter "@oomm/transformer" exec ls ./tmp
          pnpm --filter "@oomm/transformer" run artifacts -d ./tmp
          pnpm --filter "@oomm/transformer" exec ls -laR ./binding ./npm ./dist
          ls
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
